# Generated by Django 4.1.3 on 2022-11-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abc_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc_client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=100)),
                ('company_address_id', models.IntegerField()),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateField()),
                ('is_deleted', models.BooleanField()),
                ('modified_by', models.CharField(max_length=45)),
                ('modified_date', models.DateField()),
                ('phone_number', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='abc_resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc_resource_id', models.IntegerField()),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateField()),
                ('current_number_of_resources', models.IntegerField()),
                ('inventory_id', models.IntegerField()),
                ('is_deleted', models.BooleanField()),
                ('max_number_of_resources', models.IntegerField()),
                ('modified_by', models.CharField(max_length=45)),
                ('modified_date', models.DateField()),
                ('resource_name', models.CharField(max_length=45)),
                ('resource_type_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='access_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_log_id', models.IntegerField()),
                ('action', models.CharField(max_length=45)),
                ('field_name', models.CharField(max_length=45)),
                ('screen_name', models.CharField(max_length=45)),
                ('table_name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateField()),
                ('is_deleted', models.BooleanField()),
                ('modified_by', models.CharField(max_length=45)),
                ('modified_date', models.DateField()),
                ('postal_code', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='client_contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc_client_id', models.IntegerField()),
                ('client_contacts_id', models.IntegerField()),
                ('contact_id', models.IntegerField()),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateField()),
                ('is_deleted', models.BooleanField()),
                ('modified_by', models.CharField(max_length=45)),
                ('modified_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField()),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateField()),
                ('email_address', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField()),
                ('modified_by', models.CharField(max_length=45)),
                ('modified_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc_client_id', models.IntegerField()),
                ('address_id', models.IntegerField()),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateField()),
                ('inventory_id', models.IntegerField()),
                ('inventory_name', models.CharField(max_length=45)),
                ('is_deleted', models.BooleanField()),
                ('max_item_capacity', models.IntegerField()),
                ('modified_by', models.CharField(max_length=45)),
                ('modified_date', models.DateField()),
                ('storage_type_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='resource_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateField()),
                ('is_deleted', models.BooleanField()),
                ('modified_by', models.CharField(max_length=45)),
                ('modified_date', models.DateField()),
                ('resource_type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='storage_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateField()),
                ('is_deleted', models.BooleanField()),
                ('modified_by', models.CharField(max_length=45)),
                ('modified_date', models.DateField()),
                ('storage_type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=45)),
            ],
        ),
    ]
